runs:
  using: "composite"
  steps:
  - name: Set up catkin workspace
    run: |
      . /opt/ros/noetic/setup.sh
      catkin_init_workspace
      mkdir -p src/bayesopt4ros
    
  - name: Checkout repository
    uses: actions/checkout@v2
    with:
      path: "src/bayesopt4ros/"
