name: BayesOpt4ROS

on:
  push:
    branches: [ main, generate-pages ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: lukasfro/bayesopt4ros:ci  # custom image

    steps:
    - name: Set up catkin workspace
      run: |
        . /opt/ros/noetic/setup.sh
        catkin_init_workspace
        mkdir -p src/bayesopt4ros
        
    - uses: actions/checkout@v2
      with:
        path: "src/bayesopt4ros/"
        
    - name: Build catkin workspace
      run: |
        . /opt/ros/noetic/setup.sh
        catkin_make_isolated

    - name: Build sphinx documentation
      run: |
        cd src/bayesopt4ros/docs
        make html

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Unittest with pytest
      run: |
        . devel_isolated/setup.sh
        pytest src/bayesopt4ros/test/unit/

    - name: Integration test with rostest
      # Note: need to run `catkin_test_results` as this returns 1 for failure
      #       catkin_make_isolated returns 0 even if tests fail.
      run: |
        . devel_isolated/setup.sh
        catkin_make_isolated -j1 --catkin-make-args run_tests && catkin_test_results
